import { Roboto } from "next/font/google";
import Menu from "@/components/menu/menu";
import Image from "next/image";
import "./globals.css";
import type { Metadata } from "next";

const font = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["cyrillic"],
  variable: "--font-roboto",
});

export { font };

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.variable}>
        <div className="wrapper">
          <header className="header">
            <div className="header__container">
              <a href="/" className="header__logo">
                <Image
                  src="/img/header/logo.svg"
                  width={69}
                  height={89}
                  alt=""
                />

                <span>
                  Архангельское
                  <br />
                  протезно-ортопедическое
                  <br />
                  предприятие
                </span>
              </a>
              <Menu />
              <div className="header__burger">
                <span></span>
              </div>
            </div>
          </header>
        </div>

        {children}
      </body>
    </html>
  );
}
